import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { AuthProvider } from '@/context/AuthContext';
import BottomNavigation from '@/components/navbar/BottomNavigation';
import { NotificationProvider } from '@/context/NotificationContext';
import NotificationWrapper from '@/components/notifications/NotificationWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <NotificationProvider>
        <html lang='en'>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen relative flex flex-col`}
          >
            <NotificationWrapper />
            <Navbar />
            <div className='flex-grow pb-16'>{children}</div>
            <BottomNavigation />
          </body>
        </html>
      </NotificationProvider>
    </AuthProvider>
  );
}
